<a href="https://colab.research.google.com/github/luongvantuit/learn-ai-with-python/blob/master/soft-margin/BTTH5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Đường dẫn tới tệp dữ liệu
FILE_PATH = "/content/drive/My Drive/Machine Learning/Dataset/Admission_Predict.csv"

# Đọc dữ liệu
data = pd.read_csv(FILE_PATH)

# Đổi tên cột để dễ xử lý hơn
data.rename(columns={"Chance of Admit ": "Chance_of_Admit"}, inplace=True)

# Gắn nhãn nhị phân: 1 nếu >= threshold, -1 nếu < threshold
THRESHOLD = 0.7
data['Label'] = np.where(data['Chance_of_Admit'] >= THRESHOLD, 1, -1)

# Chuẩn bị dữ liệu
X = data.drop(columns=['Serial No.', 'Chance_of_Admit', 'Label']).values  # Đặc trưng
y = data['Label'].values  # Nhãn

# Chia tập dữ liệu thành huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [4]:
# Tạo và huấn luyện mô hình SVM
C = 1.0
svm_model = SVC(kernel='linear', C=C)
svm_model.fit(X_train, y_train)

SVC(kernel='linear')

In [5]:
# Đánh giá mô hình
def evaluate_model(model, X, y, dataset_name="Dataset"):
    predictions = model.predict(X)
    accuracy = accuracy_score(y, predictions)
    conf_matrix = confusion_matrix(y, predictions)
    print(f"\nĐánh giá trên {dataset_name}:")
    print(f"Accuracy: {accuracy * 100:.2f}%")
    print("Confusion Matrix:")
    print(conf_matrix)
    return accuracy, conf_matrix

# Đánh giá trên tập huấn luyện
evaluate_model(svm_model, X_train, y_train, "tập huấn luyện")

# Đánh giá trên tập kiểm tra
evaluate_model(svm_model, X_test, y_test, "tập kiểm tra")


Đánh giá trên tập huấn luyện:
Accuracy: 87.50%
Confusion Matrix:
[[ 81  20]
 [ 15 164]]

Đánh giá trên tập kiểm tra:
Accuracy: 86.67%
Confusion Matrix:
[[44  8]
 [ 8 60]]


(0.8666666666666667,
 array([[44,  8],
        [ 8, 60]]))