<a href="https://colab.research.google.com/github/luongvantuit/learn-ai-with-python/blob/master/soft-margin/VD1_BTTH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

# Random seed for reproducibility
np.random.seed(21)

# Generate synthetic data
means = [[2, 2], [4, 1]]
cov = [[0.3, 0.2], [0.2, 0.3]]
N = 10
X0 = np.random.multivariate_normal(means[0], cov, N)
X1 = np.random.multivariate_normal(means[1], cov, N)
X1[-1, :] = [2.7, 2]  # Adjust one point for edge case
X = np.hstack((X0.T, X1.T))  # Input data (2 x 20)
y = np.hstack((np.ones(N), -np.ones(N)))  # Labels (1 x 20)


In [2]:
# Predefined weights and biases for three methods
w_dual = np.array([[-5.54276837], [2.41628387]])
b_dual = 9.132906850859555

w_hinge = np.array([[-5.54923267], [2.41881653]])
b_hinge = 9.14508377

w_sklearn = np.array([[-5.54202362], [2.4156074]])
b_sklearn = 9.13241559

# Prediction function
def predict(X, w, b):
    return np.sign(X.T @ w + b)

# Accuracy function
def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred) * 100

# Confusion matrix function
def confusion_matrix_report(y_true, y_pred):
    return confusion_matrix(y_true, y_pred, labels=[1, -1])

# Run predictions and evaluations for each method
results = []
methods = ["Lagrange Dual", "Gradient Descent", "Sklearn"]
weights = [(w_dual, b_dual), (w_hinge, b_hinge), (w_sklearn, b_sklearn)]

for method, (w, b) in zip(methods, weights):
    y_pred = predict(X, w, b)
    acc = accuracy(y, y_pred)
    cm = confusion_matrix_report(y, y_pred)
    results.append({
        "Method": method,
        "Weights": w.T,
        "Bias": b,
        "Accuracy (%)": acc,
        "Confusion Matrix": cm
    })

# Print results
for res in results:
    print(f"Method: {res['Method']}")
    print(f"Weights: {res['Weights']}")
    print(f"Bias: {res['Bias']}")
    print(f"Accuracy: {res['Accuracy (%)']:.2f}%")
    print(f"Confusion Matrix:\n{res['Confusion Matrix']}\n")

Method: Lagrange Dual
Weights: [[-5.54276837  2.41628387]]
Bias: 9.132906850859555
Accuracy: 50.00%
Confusion Matrix:
[[10  0]
 [ 0 10]]

Method: Gradient Descent
Weights: [[-5.54923267  2.41881653]]
Bias: 9.14508377
Accuracy: 50.00%
Confusion Matrix:
[[10  0]
 [ 0 10]]

Method: Sklearn
Weights: [[-5.54202362  2.4156074 ]]
Bias: 9.13241559
Accuracy: 50.00%
Confusion Matrix:
[[10  0]
 [ 0 10]]



All three methods perform similarly in terms of accuracy for this dataset. However, the Scikit-learn implementation is recommended for most practical use cases due to its ease of use and computational efficiency. Lagrange Dual is suitable for theoretical exploration and understanding the SVM formulation, while Gradient Descent is valuable for custom implementations and cases requiring iterative optimization.